#!/usr/bin/env bash

set -e

[ "$SKIP_PRE_COMMIT" = 1 ] && exit 0

. "$(dirname "$0")/_/husky.sh"

echo "→ Looking for spelling errors in staged files..."
exec git diff --cached --name-only | pnpm cspell --show-suggestions --show-context --no-progress --no-must-find-files --file-list stdin
